development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: realtime_chat_development

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: realtime_chat_production
